# Generated by Django 3.2 on 2025-05-26 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetology', '0002_login_pharmacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(blank=True, max_length=50, null=True)),
                ('patientUID', models.CharField(max_length=10)),
                ('patientName', models.CharField(max_length=255)),
                ('mobileNumber', models.CharField(max_length=11)),
                ('appointmentTime', models.CharField(max_length=1000)),
                ('appointmentDate', models.DateField()),
                ('purposeOfVisit', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BillingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(blank=True, max_length=50, null=True)),
                ('patientUID', models.CharField(max_length=10)),
                ('patientName', models.CharField(max_length=100)),
                ('appointmentDate', models.CharField(max_length=500)),
                ('table_data', models.JSONField()),
                ('netAmount', models.CharField(max_length=500)),
                ('discount', models.CharField(max_length=500)),
                ('paymentType', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], max_length=10)),
                ('billNumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Findings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('branch_code', models.CharField(blank=True, max_length=50, null=True)),
                ('patientName', models.CharField(max_length=255)),
                ('mobileNumber', models.CharField(max_length=11)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('patientUID', models.CharField(blank=True, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('purposeOfVisit', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(blank=True, max_length=50, null=True)),
                ('appointmentDate', models.CharField(max_length=255)),
                ('patientName', models.CharField(max_length=255)),
                ('patientUID', models.CharField(max_length=255)),
                ('procedures', models.JSONField()),
                ('procedureNetAmount', models.CharField(max_length=255)),
                ('consumerNetAmount', models.CharField(max_length=255)),
                ('consumer', models.JSONField()),
                ('PaymentType', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], max_length=10)),
                ('consumerBillNumber', models.CharField(max_length=50)),
                ('procedureBillNumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(blank=True, max_length=50, null=True)),
                ('patientName', models.CharField(max_length=100)),
                ('patientUID', models.CharField(max_length=100)),
                ('mobileNumber', models.CharField(max_length=100)),
                ('diagnosis', models.CharField(blank=True, max_length=1500)),
                ('complaints', models.JSONField()),
                ('findings', models.CharField(blank=True, max_length=1500)),
                ('prescription', models.CharField(blank=True, max_length=1500)),
                ('plans', models.CharField(blank=True, max_length=1500)),
                ('tests', models.CharField(blank=True, max_length=1500)),
                ('vital', models.JSONField()),
                ('proceduresList', models.JSONField()),
                ('nextVisit', models.CharField(blank=True, max_length=100, null=True)),
                ('appointmentDate', models.CharField(blank=True, max_length=100)),
                ('time', models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(blank=True, max_length=50, null=True)),
                ('patientUID', models.CharField(max_length=10)),
                ('patientName', models.CharField(max_length=100)),
                ('mobileNumber', models.CharField(max_length=15)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('pulseRate', models.CharField(max_length=10)),
                ('bloodPressure', models.CharField(max_length=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='register',
            old_name='confirmPassword',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='CGST_percentage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='CGST_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='SGST_percentage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='SGST_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='batch_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='branch_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='medicine_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='new_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='old_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='branch_code',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='medicine_name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(blank=True, max_length=50, null=True)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetology.patient')),
            ],
        ),
    ]
